- name: Launch Database Container
  docker_container:
    name: database
    image: ap0g/tp-devops-database:latest
    state: started
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: app-network
