- name: Launch Database Container
  docker_container:
    name: database
    image: ap0g/tp-devops-database:latest
    state: started
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    networks:
      - name: app-network
