name: CI devops 2023 - Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI devops 2023 - Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker/simple-api-student-main
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker/database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and push httpd Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker/Frontend
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: true
